DROP TABLE IF EXISTS `links`;
CREATE TABLE `links` (
`ID` int(11) unsigned NOT NULL,
`links` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
`title` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
INSERT INTO `links` VALUES (0, 'https://secureservercdn.net/198.71.233.109/nvx.fe0.myftpupload.com/wp-content/uploads/2020/06/2-1-1-Sonoma-Application-Form-2019.doc', '');
INSERT INTO `links` VALUES (1, 'mailto:211sonoma@icfs.org', 'Email');
INSERT INTO `links` VALUES (2, 'https://secureservercdn.net/198.71.233.109/nvx.fe0.myftpupload.com/wp-content/uploads/2020/10/2-1-1-Sonoma-County-Inclusion-Exclusion-Policy.pdf', '');
INSERT INTO `links` VALUES (3, 'https://app.powerbi.com/view?r=eyJrIjoiMDczOTczYzQtYWZkNS00OTNlLWFjZDAtYzljYWNmMTg2NjUxIiwidCI6ImI4NTFhY2ZmLTM5ODgtNDY1OC04OWVhLWJmM2M3NmRkZTlhNiIsImMiOjZ9', 'Microsoft Power BI');
INSERT INTO `links` VALUES (4, 'https://unitedwaywinecountry.org/', 'Home - United Way of the Wine Country');
INSERT INTO `links` VALUES (5, 'http://www.211.org/', '211.org');
INSERT INTO `links` VALUES (6, 'https://www.fcc.gov/consumers/guides/dial-211-essential-community-services', 'Dial 211 for Essential Community Services | Federal Communications Commission');
INSERT INTO `links` VALUES (7, 'https://unitedwaywinecountry.org/servlet/eAndar.article/4/United-Way-of-the-Wine-Country', 'Page not found - United Way of the Wine Country');
INSERT INTO `links` VALUES (8, 'https://socoemergency.org/home/recover/2019-flood/', 'Sucuri WebSite Firewall - Access Denied');
INSERT INTO `links` VALUES (9, 'https://rocsonomacounty.org/', 'ROC Sonoma County Fire Recovery');
INSERT INTO `links` VALUES (10, 'https://socoemergency.org/home/prepared', 'Sucuri WebSite Firewall - Access Denied');
INSERT INTO `links` VALUES (11, 'https://www.211ca.org/search/?taxonomyCode=BH-3800.7000&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (12, 'https://www.211ca.org/search/?taxonomyCode=BH-3800.7250&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (13, 'https://www.211ca.org/search/?taxonomyCode=PH-3300.2750&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (14, 'https://www.211ca.org/search/?taxonomyCode=BH-3000.1800-950&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (15, 'https://www.211ca.org/search/?taxonomyCode=BH-3000.3550&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (16, 'https://www.211ca.org/search/?taxonomyCode=BH-3000.3500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (17, 'https://www.211ca.org/search/?taxonomyCode=BH-1800.8500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (18, 'https://www.211ca.org/search/?taxonomyCode=BH-8600&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (19, 'https://www.211ca.org/search/?taxonomyCode=BH-1800.1500-100&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (20, 'https://www.211ca.org/search/?taxonomyCode=BH-1800.1500-700&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (21, 'https://www.211ca.org/search/?taxonomyCode=BH-1800.1500-800&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (22, 'https://www.211ca.org/search/?taxonomyCode=BH-1800.3500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (23, 'https://www.211ca.org/search/?taxonomyCode=BM-6500.6500-450&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (24, 'https://www.211ca.org/search/?taxonomyCode=BM-6500.6500-710&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (25, 'https://www.211ca.org/search/?taxonomyCode=BM-6500.6500-850&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (26, 'https://www.211ca.org/search/?taxonomyCode=BD-5000.8300&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (27, 'https://www.211ca.org/search/?taxonomyCode=BH-7000.4600&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (28, 'https://www.211ca.org/search/?taxonomyCode=BH-7000.8100&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (29, 'https://www.211ca.org/search/?taxonomyCode=BH-3700&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (30, 'https://www.211ca.org/search/?taxonomyCode=BH-8500.8000&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (31, 'https://www.211ca.org/search/?taxonomyCode=FT-4500.8550&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (32, 'http://benefitkitchen.com/icfs', 'icfs – Benefit Kitchen');
INSERT INTO `links` VALUES (33, 'https://www.211ca.org/search/?taxonomyCode=ND-1500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (34, 'https://www.211ca.org/search/?taxonomyCode=ND-2000&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (35, 'https://www.211ca.org/search/?taxonomyCode=ND-3500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (36, 'https://www.211ca.org/search/?taxonomyCode=ND-6500.9800&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (37, 'https://www.211ca.org/search/?taxonomyCode=ND-6500.9200&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (38, 'https://www.211ca.org/search/?taxonomyCode=DM-1500.1500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (39, 'https://www.211ca.org/search/?taxonomyCode=NL-1000.8500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (40, 'https://www.211ca.org/search/?taxonomyCode=NL-1000.2500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (41, 'https://www.211ca.org/search/?taxonomyCode=NS-1800.8000&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (42, 'https://www.211ca.org/search/?taxonomyCode=NS-7000.8000&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (43, 'https://www.211ca.org/search/?taxonomyCode=NS-1800.8100&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (44, 'https://www.211ca.org/search/?taxonomyCode=NS-9000.9000&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (45, 'https://www.211ca.org/search/?taxonomyCode=NL-6000.2000&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (46, 'https://www.211ca.org/search/?taxonomyCode=NL-5000.5000&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (47, 'https://www.211ca.org/search/?taxonomyCode=NS-8000.5000&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (48, 'https://www.211ca.org/search/?taxonomyCode=FT-1000.9000&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (49, 'https://www.211ca.org/search/?taxonomyCode=BV-8900.9300-180&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (50, 'https://www.211ca.org/search/?taxonomyCode=BV-8900.9300-250&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (51, 'https://www.211ca.org/search/?taxonomyCode=BD-5000.3500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (52, 'https://www.211ca.org/search/?taxonomyCode=BM-5050.1500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (53, 'https://www.211ca.org/search/?taxonomyCode=BV-8900.1700&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (54, 'https://www.211ca.org/search/?taxonomyCode=FT-3000.1600&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (55, 'https://www.211ca.org/search/?taxonomyCode=BM-6500.1500-250&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (56, 'https://www.211ca.org/search/?taxonomyCode=BM-6500.1500-100&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (57, 'https://www.211ca.org/search/?taxonomyCode=BM-3000.2000-100&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (58, 'https://www.211ca.org/search/?taxonomyCode=BM-3000.0500-700&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (59, 'https://www.211ca.org/search/?taxonomyCode=NL-6000.9500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (60, 'https://www.211ca.org/search/?taxonomyCode=BD-1800.2000&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (61, 'https://www.211ca.org/search/?taxonomyCode=BD-1800.1000&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (62, 'https://www.211ca.org/search/?taxonomyCode=BD-2400.2250&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (63, 'https://www.211ca.org/search/?taxonomyCode=PH-3300.1800&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (64, 'https://www.211ca.org/search/?taxonomyCode=BD-5000.1500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (65, 'https://www.211ca.org/search/?taxonomyCode=RP-1500.1400-500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (66, 'https://www.211ca.org/search/?taxonomyCode=RP-1500.1400-200&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (67, 'https://www.211ca.org/search/?taxonomyCode=RP-1500.1400-800&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (68, 'https://www.211ca.org/search/?taxonomyCode=RP-1500.3300&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (69, 'https://www.211ca.org/search/?taxonomyCode=RP-1500.1400-150&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (70, 'https://www.211ca.org/search/?taxonomyCode=RP-1500.1400-700&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (71, 'https://www.211ca.org/search/?taxonomyCode=RP-1500.1400-750&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (72, 'https://www.211ca.org/search/?taxonomyCode=RP-1500.3400-650&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (73, 'https://www.211ca.org/search/?taxonomyCode=RP-1500.1400-300&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (74, 'https://www.211ca.org/search/?taxonomyCode=RF-8380&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (75, 'https://www.211ca.org/search/?taxonomyCode=PH-6500.1500-140&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (76, 'https://www.211ca.org/search/?taxonomyCode=PH-6500.0500-180&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (77, 'https://www.211ca.org/search/?taxonomyCode=PD-0700.0400&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (78, 'https://www.211ca.org/search/?taxonomyCode=FL-6500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (79, 'https://www.211ca.org/search/?taxonomyCode=FL-8200&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (80, 'https://www.211ca.org/search/?taxonomyCode=JR-1900&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (81, 'https://www.211ca.org/search/?taxonomyCode=LH-2700.6500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (82, 'https://www.211ca.org/search/?taxonomyCode=BT-8750.8600&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (83, 'https://www.211ca.org/search/?taxonomyCode=BT-4500.4700&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (84, 'https://www.211ca.org/search/?taxonomyCode=BT-4800.7000&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (85, 'https://www.211ca.org/search/?taxonomyCode=BT-4500.6500-170&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (86, 'https://www.211ca.org/search/?taxonomyCode=BT-4500.6500-500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (87, 'https://www.211ca.org/search/?taxonomyCode=LH-6300.5600&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (88, 'https://www.211ca.org/search/?taxonomyCode=BT-4500.6500-800&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (89, 'https://www.211ca.org/search/?taxonomyCode=LN&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (90, 'https://www.211ca.org/search/?taxonomyCode=LL-3000&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (91, 'https://www.211ca.org/search/?taxonomyCode=LH-3500.0200&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (92, 'https://www.211ca.org/search/?taxonomyCode=NL-5000.8000-150&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (93, 'https://www.211ca.org/search/?taxonomyCode=LH-3500.2500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (94, 'https://www.211ca.org/search/?taxonomyCode=LH-5100.5000&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (95, 'https://www.211ca.org/search/?taxonomyCode=LH-5100.6500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (96, 'https://www.211ca.org/search/?taxonomyCode=LF-4900.1000&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (97, 'https://www.211ca.org/search/?taxonomyCode=LF-4900.2000&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (98, 'https://www.211ca.org/search/?taxonomyCode=LF-4900.2150&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (99, 'https://www.211ca.org/search/?taxonomyCode=LF-4900.8600&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (100, 'https://www.211ca.org/search/?taxonomyCode=LF-4900.1700&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (101, 'https://www.211ca.org/search/?taxonomyCode=LF-4900.1500-500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (102, 'https://www.211ca.org/search/?taxonomyCode=LF-7000.1730&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (103, 'https://www.211ca.org/search/?taxonomyCode=LH-2600.6500-500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (104, 'https://www.211ca.org/search/?taxonomyCode=LT-8500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (105, 'https://www.211ca.org/search/?taxonomyCode=LH-2700.1700&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (106, 'https://www.211ca.org/search/?taxonomyCode=LV-1600&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (107, 'https://www.211ca.org/search/?taxonomyCode=LH-2600.1700&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (108, 'https://www.211ca.org/search/?taxonomyCode=LT-3400&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (109, 'https://www.211ca.org/search/?taxonomyCode=LJ-2000.1000&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (110, 'https://www.211ca.org/search/?taxonomyCode=LJ-2000.6750&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (111, 'https://www.211ca.org/search/?taxonomyCode=LF-4900.8000&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (112, 'https://www.211ca.org/search/?taxonomyCode=LF-4900.2400&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (113, 'https://www.211ca.org/search/?taxonomyCode=LJ-5000.6600&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (114, 'https://www.211ca.org/search/?taxonomyCode=NL-3000.3300&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (115, 'https://www.211ca.org/search/?taxonomyCode=PH-3300.6500&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (116, 'https://www.211ca.org/search/?taxonomyCode=PN-8100.1400&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (117, 'https://www.211ca.org/search/?taxonomyCode=LT-3000&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (118, 'https://www.211ca.org/search/?taxonomyCode=LH-2600.3000&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (119, 'https://www.211ca.org/search/?taxonomyCode=RP-1400.2500&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (120, 'https://www.211ca.org/search/?taxonomyCode=RF-2500&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (121, 'https://www.211ca.org/search/?taxonomyCode=RP-1400.8000-155&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (122, 'https://www.211ca.org/search/?taxonomyCode=RP-1400.8000-050&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (123, 'https://www.211ca.org/search/?taxonomyCode=RP-1400.8000-500&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (124, 'https://www.211ca.org/search/?taxonomyCode=RP-1400.8000-070&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (125, 'https://www.211ca.org/search/?taxonomyCode=RP-1400.8000-675&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (126, 'https://www.211ca.org/search/?taxonomyCode=RP-1400.8000-100&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (127, 'https://www.211ca.org/search/?taxonomyCode=PN-8100.1000-250&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (128, 'https://www.211ca.org/search/?taxonomyCode=PN-8100.1000-100&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (129, 'https://www.211ca.org/search/?taxonomyCode=PN-8100.1000-650&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (130, 'https://www.211ca.org/search/?taxonomyCode=RX-8450.8000-180&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (131, 'https://www.211ca.org/search/?taxonomyCode=PN-8100.0500-070&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (132, 'https://www.211ca.org/search/?taxonomyCode=PN-8100.0500-180&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (133, 'https://www.211ca.org/search/?taxonomyCode=PN-8100.0500-230&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (134, 'https://www.211ca.org/search/?taxonomyCode=PN-8100.0500-030&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (135, 'https://www.211ca.org/search/?taxonomyCode=PN-8100.0500-250&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (136, 'https://www.211ca.org/search/?taxonomyCode=PN-8100.0500-800&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (137, 'https://www.211ca.org/search/?taxonomyCode=RP-1400.8000-020.15&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (138, 'https://www.211ca.org/search/?taxonomyCode=RP-1400.8000-020.18&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (139, 'https://www.211ca.org/search/?taxonomyCode=RP-1400.8000-020.21&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (140, 'https://www.211ca.org/search/?taxonomyCode=PN-8100.0200-180&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (141, 'https://www.211ca.org/search/?taxonomyCode=RP-1400.8000-800&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (142, 'https://www.211ca.org/search/?taxonomyCode=PN-8100.3000&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (143, 'https://www.211ca.org/search/?taxonomyCode=PN-8100.5000&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (144, 'https://www.211ca.org/search/?taxonomyCode=PN-8100.6500-650&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (145, 'https://www.211ca.org/search/?taxonomyCode=PN-8100.6500-030&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (146, 'https://www.211ca.org/search/?taxonomyCode=TD-1600.3100-950&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (147, 'https://www.211ca.org/search/?taxonomyCode=PN-8100.6500-750&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (148, 'https://www.211ca.org/search/?taxonomyCode=PN-8100.0500-900&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (149, 'https://www.211ca.org/search/?taxonomyCode=PN-8100.4500-400&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (150, 'https://www.211ca.org/search/?taxonomyCode=PN-8100.1000-080&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (151, 'https://www.211ca.org/search/?taxonomyCode=RP-6400.8000-650&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (152, 'https://www.211ca.org/search/?taxonomyCode=RM-3300.6500-150&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (153, 'https://www.211ca.org/search/?taxonomyCode=RX-8250.0500&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (154, 'https://www.211ca.org/search/?taxonomyCode=RX-8250.1700&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (155, 'https://www.211ca.org/search/?taxonomyCode=RX-8450.8000-050&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (156, 'https://www.211ca.org/search/?taxonomyCode=RX-8470.8350-050&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (157, 'https://www.211ca.org/search/?taxonomyCode=RX-8450.1150-150&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (158, 'https://www.211ca.org/search/?taxonomyCode=RX-8450.7000-700&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (159, 'https://www.211ca.org/search/?taxonomyCode=RX-1700.0500&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (160, 'https://www.211ca.org/search/?taxonomyCode=RX-8500&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (161, 'https://www.211ca.org/search/?taxonomyCode=RX-8450.6600-600&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (162, 'https://www.211ca.org/search/?taxonomyCode=RX-8470.8350-180&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (163, 'https://www.211ca.org/search/?taxonomyCode=RX-8450.1150-180&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (164, 'https://www.211ca.org/search/?taxonomyCode=RX-8450.7000-750&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (165, 'https://www.211ca.org/search/?taxonomyCode=RX-1700.1700&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (166, 'https://www.211ca.org/search/?taxonomyCode=RX-8450.6600-650&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (167, 'http://recorder.countyofventura.org/county-recorder/vital-records/', 'Ventura County, CA – County Clerk and Recorder / Registrar of Voters');
INSERT INTO `links` VALUES (168, 'http://www.dmv.ca.gov/portal/dmv/detail/dl/dl_info', 'Driver License or ID Card Renewal - California DMV');
INSERT INTO `links` VALUES (169, 'https://www.ssa.gov/ssnumber/', 'Social Security Number and Card | SSA');
INSERT INTO `links` VALUES (170, 'https://secureservercdn.net/198.71.233.109/nvx.fe0.myftpupload.com/wp-content/uploads/2015/03/72-hour-checklist.pdf', '');
INSERT INTO `links` VALUES (171, 'https://secureservercdn.net/198.71.233.109/nvx.fe0.myftpupload.com/wp-content/uploads/2016/02/Top_10_Things_You_Can_Do_for_a_Successful_Reentry_into_the_Community.pdf', '');
INSERT INTO `links` VALUES (172, 'https://www.211ca.org/search/?taxonomyCode=PS-6500&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (173, 'https://www.211ca.org/search/?taxonomyCode=PH-6100.6800&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (174, 'https://www.211ca.org/search/?taxonomyCode=PH-6100.1550&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (175, 'https://www.211ca.org/search/?taxonomyCode=PH-6100.1600&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (176, 'https://www.211ca.org/search/?taxonomyCode=PH-6100.1800&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (177, 'https://www.211ca.org/search/?taxonomyCode=LJ-5000.1000&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (178, 'https://www.211ca.org/search/?taxonomyCode=LJ-5000.1500&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (179, 'https://www.211ca.org/search/?taxonomyCode=BM-6500.1500-150&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (180, 'https://www.211ca.org/search/?taxonomyCode=LF-7000.9500&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (181, 'https://www.211ca.org/search/?taxonomyCode=RP-1400.8000-655&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (182, 'https://www.211ca.org/search/?taxonomyCode=JR-8200.6500-350&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (183, 'https://www.211ca.org/search/?taxonomyCode=JR-8200.8500-160&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (184, 'https://www.211ca.org/search/?taxonomyCode=LH-2700.2000-150&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (185, 'https://www.211ca.org/search/?taxonomyCode=PH-2400.1500&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (186, 'https://www.211ca.org/search/?taxonomyCode=NL-3000.1500&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (187, 'https://www.211ca.org/search/?taxonomyCode=PH-0300.0300&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (188, 'https://www.211ca.org/search/?taxonomyCode=LJ-5000.8000&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (189, 'https://www.211ca.org/search/?taxonomyCode=TM-5100&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (190, 'https://www.211ca.org/search/?taxonomyCode=PH-1400.5000-100&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (191, 'https://www.211ca.org/search/?taxonomyCode=PS-9800&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (192, 'https://www.211ca.org/search/?taxonomyCode=PH-6200.4500&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (193, 'https://www.211ca.org/search/?taxonomyCode=TC-5500.9800&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (194, 'https://www.211ca.org/search/?taxonomyCode=PL-7000.4360&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (195, 'https://www.211ca.org/search/?taxonomyCode=TJ-3200.9500&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (196, 'https://www.211ca.org/search/?taxonomyCode=HH-7920&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (197, 'https://www.211ca.org/search/?taxonomyCode=TC-5500.8000&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (198, 'https://www.211ca.org/search/?taxonomyCode=TD-1100.6500-050&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (199, 'https://www.211ca.org/search/?taxonomyCode=RP-1400.8000-270&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (200, 'https://www.211ca.org/search/?taxonomyCode=PH-0320&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (201, ' https://211sonoma.org/education/', '');
INSERT INTO `links` VALUES (202, 'https://www.211ca.org/search/?taxonomyCode=DF-7000.1200&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (203, 'https://www.211ca.org/search/?taxonomyCode=DF-7000.1700-300&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (204, 'https://www.211ca.org/search/?taxonomyCode=DF-7000.5500&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (205, 'https://www.211ca.org/search/?taxonomyCode=DF-7000.3300&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (206, 'https://www.211ca.org/search/?taxonomyCode=DF-7000.5000&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (207, 'https://www.211ca.org/search/?taxonomyCode=DF-7000.1800&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (208, 'https://www.211ca.org/search/?taxonomyCode=DF-7000.6650&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (209, 'https://www.211ca.org/search/?taxonomyCode=DF-7000.8250&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (210, 'https://www.211ca.org/search/?taxonomyCode=FT-3200&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (211, 'https://www.211ca.org/search/?taxonomyCode=FT-4800&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (212, 'https://www.211ca.org/search/?taxonomyCode=FP-8000&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (213, 'https://www.211ca.org/search/?taxonomyCode=FT-3000.1500&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (214, 'https://www.211ca.org/search/?taxonomyCode=FT-3000.1700&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (215, 'https://www.211ca.org/search/?taxonomyCode=FT-3600&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (216, 'https://www.211ca.org/search/?taxonomyCode=FT-3000.1750&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (217, 'https://www.211ca.org/search/?taxonomyCode=FT-6940&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (218, 'https://www.211ca.org/search/?taxonomyCode=FN-1900.2500&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (219, 'https://www.211ca.org/search/?taxonomyCode=FT-1800.1850&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (220, 'https://www.211ca.org/search/?taxonomyCode=FT-1800.3000&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (221, 'https://www.211ca.org/search/?taxonomyCode=FC-8200.3500&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (222, 'https://www.211ca.org/search/?taxonomyCode=FC-8200.8100-800&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (223, 'https://www.211ca.org/search/?taxonomyCode=FC-8200.8100-900&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (224, 'https://www.211ca.org/search/?taxonomyCode=FC-8200.1500&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (225, 'https://www.211ca.org/search/?taxonomyCode=FC-8200.1550&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (226, 'https://secureservercdn.net/198.71.233.109/nvx.fe0.myftpupload.com/wp-content/uploads/2019/07/Que-hacer-Sonoma-1-2.pdf', '');
INSERT INTO `links` VALUES (227, 'http://sonomacounty.ca.gov/Probation/', '
	Probation | Departments & Agencies | County of Sonoma
');
INSERT INTO `links` VALUES (228, 'https://sonomacounty.ca.gov/CRA/Clerk-Recorder/Vital-Records/Birth-Certificates/', '
	Birth Certificates | Clerk - Recorder - Assessor - Registrar of Voters | County of Sonoma
');
INSERT INTO `links` VALUES (229, 'https://www.dmv.ca.gov/portal/dmv/detail/dl/dl_info', 'Driver License or ID Card Renewal - California DMV');
INSERT INTO `links` VALUES (230, 'https://www.cdc.gov/nchs/w2w/index.htm', 'Where to Write for Vital Records - Homepage');
INSERT INTO `links` VALUES (231, 'https://www.211ca.org/search/?taxonomyCode=BT-4500.6500-280&location=sonoma+county+ca#googtrans(es)', '');
INSERT INTO `links` VALUES (232, 'https://sonomacounty.ca.gov/Human-Services/Economic-Assistance/Health-Care-Benefits/Medi-Cal-and-County-Medical-Services-Program/', '
	Medi-Cal & County Medical Services Program | Health Care Benefits | Economic Assistance | Human Services | County of Sonoma
');
INSERT INTO `links` VALUES (233, 'https://www.coveredca.com/', 'Covered Californiaâ¢ | The Official Site of Californias Health Insurance Marketplace');
INSERT INTO `links` VALUES (234, 'https://www.dfeh.ca.gov/Employment/', 'Employment | DFEH');
INSERT INTO `links` VALUES (235, 'http://sonomacounty.ca.gov/Human-Services/Employment-and-Training/SonomaWORKS/', '
	SonomaWORKS | Employment and Training | Human Services | County of Sonoma
');
INSERT INTO `links` VALUES (236, 'https://sonomacounty.ca.gov/Human-Services/Economic-Assistance/General-Assistance/', '
	General Assistance | Economic Assistance | Human Services | County of Sonoma
');
INSERT INTO `links` VALUES (237, 'https://www.ssa.gov/benefits/ssi/', 'Supplemental Security Income (SSI) Benefits | SSA');
INSERT INTO `links` VALUES (238, 'https://www.ssa.gov/benefits/disability/', 'Disability Benefits | SSA');
INSERT INTO `links` VALUES (239, 'https://www.ssa.gov/espanol/beneficios/ssi/', 'Seguridad de Ingreso Suplementario (SSI) | Administración del Seguro Social');
INSERT INTO `links` VALUES (240, 'https://www.acf.hhs.gov/sites/default/files/programs/css/ca_cs_order.pdf', '');
INSERT INTO `links` VALUES (241, 'https://secureservercdn.net/198.71.233.109/nvx.fe0.myftpupload.com/wp-content/uploads/2018/10/lecture.jpg', '');
INSERT INTO `links` VALUES (242, 'https://home.cccapply.org/money/california-college-promise-grant', 'California College Promise Grant');
INSERT INTO `links` VALUES (243, 'https://studentaid.ed.gov/', '');
INSERT INTO `links` VALUES (244, 'https://www.211ca.org/search/?taxonomyCode=HH-0500.2500-050&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (245, 'https://www.211ca.org/search/?taxonomyCode=HH-4500.0500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (246, 'https://www.211ca.org/search/?taxonomyCode=TJ-4400.6500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (247, 'https://www.211ca.org/search/?taxonomyCode=PL-7400.1500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (248, 'https://secureservercdn.net/198.71.233.109/nvx.fe0.myftpupload.com/wp-content/uploads/2019/07/72-Hour-Checklist-Sonoma.pdf', '');
INSERT INTO `links` VALUES (249, 'https://secureservercdn.net/198.71.233.109/nvx.fe0.myftpupload.com/wp-content/uploads/2018/12/Tips-for-Reentry-Success-VC-12.11.pdf', '');
INSERT INTO `links` VALUES (250, 'http://www.211.org.', '211.org');
INSERT INTO `links` VALUES (251, 'https://getfood.refb.org/', 'Get Food | Redwood Empire Food Bank');
INSERT INTO `links` VALUES (252, 'https://www.google.com/maps/d/viewer?mid=12sGarVKPhpZMJsoQNhED65mJilzG6245&ll=38.51774044915148%2C-122.9129044&z=10', 'SCOE School Lunch Sites (COVID-19) - Google My Maps');
INSERT INTO `links` VALUES (253, 'https://socoemergency.org/emergency/novel-coronavirus/resources-information/financial-assistance-for-residents/', 'Sucuri WebSite Firewall - Access Denied');
INSERT INTO `links` VALUES (254, 'https://socoemergency.org/order-of-the-health-officer-shelter-in-place/', 'Sucuri WebSite Firewall - Access Denied');
INSERT INTO `links` VALUES (255, 'https://sonomacounty.ca.gov/Health/Information-About-Coronavirus/#googtrans(es)', 'Sucuri WebSite Firewall - Access Denied');
INSERT INTO `links` VALUES (256, 'https://www.211ca.org/search/?taxonomyCode=HH-0500.2500-250&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (257, 'https://www.211ca.org/search/?taxonomyCode=HH-0500.8000-150&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (258, 'https://www.211ca.org/search/?taxonomyCode=HH-0500.0500&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (259, 'https://www.211ca.org/search/?taxonomyCode=HH-5000&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (260, 'https://www.211ca.org/search/?taxonomyCode=HL-8700&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (261, 'https://www.211ca.org/search/?taxonomyCode=FT-8000.8000&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (262, 'https://www.211ca.org/search/?taxonomyCode=HD-8200&location=sonoma+county+ca#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers. - Search Results');
INSERT INTO `links` VALUES (263, 'http://www.211ca.org#googtrans(es)', 'California 2-1-1 Get Connected. Get Answers.');
INSERT INTO `links` VALUES (264, 'https://www.google.com/maps/d/u/0/viewer?mid=12sGarVKPhpZMJsoQNhED65mJilzG6245&ll=38.51774044915148%2C-122.9129044&z=10', 'SCOE School Lunch Sites (COVID-19) - Google My Maps');
INSERT INTO `links` VALUES (265, 'https://sonomacounty.ca.gov/Health/Information-About-Coronavirus/', 'Sucuri WebSite Firewall - Access Denied');
